### ISSUE TITLE
Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by lding2019** [shuangsong0110/NeuPred#1]
Although I can successfully open the web page, it failed when I use command "devtools::install_github("shuangsong0110/NeuPred")" to install the R package. Could you please check if it is the problem of the repo connection?

**Comment by shuangsong0110** [comment]
The problem has been fixed. Could you please try it again?

**Comment by lding2019** [comment]
Thx a lot, it works.

**Comment by lding2019** [comment]
Hi shuangsong, 

I also saw a new tool, LDER, for heritability estimation in your Github. I wonder if the manuscript could be shared? I'm really interested in the new approach but I didn't got any description online. Thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuangsong0110/NeuPred"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuangsong0110/NeuPred] Failed to install 'unknown package' from GitHub (Issue #1)





 
The problem has been fixed. Could you please try it again?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shuangsong0110** [comment]
Hi~
Thanks for your interest. The paper is still under review. I will send you a link when it is online.

Best,
Shuang
